entity: 'whatchang'
permute_mode: False
train_batch_size: 128
valid_batch_size: 16
lr: 0.00007367780446935216
batch_size: train_batch_size
epochs: 200
seed: 777
model_name: 'vae'
mode: 'task'
temperature: 1.7751276003136511
use_wandb: False
use_scheduler: False
scheduler_name: 'LROn'
patience: 200
loss_mode: 'our_loss'