entity: 'whatchang'
permute_mode: None
train_batch_size: 128
valid_batch_size: 16
lr: 1e-2
batch_size: train_batch_size
epochs: 1000
seed: 777
model_name: 'vae'
mode: 'task'
temperature: 1
use_wandb: True
use_scheduler: False
scheduler_name: 'LROn'
patience: 200